# Generated by Django 4.0.2 on 2022-02-22 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='day_of_week',
        ),
    ]
