# Generated by Django 4.0.2 on 2022-02-22 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dayofweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='day_of_week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dayofweek'),
        ),
    ]
