# Generated by Django 4.0.2 on 2022-02-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_point_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='entrance',
            field=models.TimeField(null=True),
        ),
    ]
